### ISSUE TITLE
Correcciones Zaragoza

### ISSUE THREAD

**Issue by msevilla00** [geoinquietos-org/geoinquietos-org.github.io#28]
Desde el grupo zaragozano nos gustaría salir como "Mapeado Colaborativo - Geoinquietos Zaragoza" pues se nos conoce más por el grupo de "Mapeado Colaborativo". Así mismo tenemos una web que es http://mapcolabora.org por lo que sería conveniente sustituir el enlace al grupo que tenemos en Google por esta.
Muchas gracias

**Comment by jsanz** [comment]
Se arregló en https://github.com/geoinquietos-org/geoinquietos-org.github.io/commit/06146d37d98d78253c4b61e3345d9bb7bc48d881#diff-04ddb929c308fd24acd2a8c20c32573a
